Vagrant.configure("2") do |config|

    config.vm.define "docker01" do |docker01|
        docker01.vm.box = "generic/ubuntu2004"
        docker01.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        docker01.vm.provider "virtualbox" do |v|
            v.name = "docker01"
            v.memory = 2048
            v.cpus = 4
          end
          docker01.vm.network "public_network", bridge: "Ethernet", ip: "192.168.1.236"
        # Update the machine
        config.vm.provision "shell", path: "./scripts/master_init.sh"
    end

    # config.vm.define "docker02" do |docker02|
    #     docker02.vm.box = "generic/ubuntu2004"
    #     docker02.vm.provider "virtualbox" do |v|
    #         v.name = "docker02"
    #         v.memory = 2048
    #         v.cpus = 4
    #       end
    #       docker02.vm.network "public_network", bridge: "Ethernet", ip: "192.168.1.237"
    #     # Update the machine
    #     config.vm.provision "shell", path: "./scripts/slave_init.sh"
    # end
    
    # config.vm.define "docker03" do |docker03|
    #     docker03.vm.box = "generic/ubuntu2004"
    #     docker03.vm.provider "virtualbox" do |v|
    #         v.name = "docker03"
    #         v.memory = 2048
    #         v.cpus = 4
    #       end
    #       docker03.vm.network "public_network", bridge: "Ethernet", ip: "192.168.1.238"
    #     # Update the machine
    #     config.vm.provision "shell", path: "./scripts/slave_init.sh"
    # end
end