Vagrant.configure("2") do |config|

    config.vm.define "docker01" do |docker01|
        docker01.vm.box = "generic/ubuntu2004"
        docker01.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        docker01.vm.hostname = "docker01.dob.lab"
        docker01.vm.provider "virtualbox" do |v|
            v.name = "docker01"
            v.memory = 2048
            v.cpus = 4
          end
          docker01.vm.network "public_network", bridge: "Ethernet", ip: "192.168.1.236"
        # Initialization scripts
        docker01.vm.provision "shell", path: "./scripts/docker_init.sh"
        docker01.vm.provision "shell", path: "./scripts/master_swarm_init.sh"

    end

    config.vm.define "docker02" do |docker02|
        docker02.vm.box = "generic/ubuntu2004"
        docker02.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        docker02.vm.hostname = "docker02.dob.lab"
        docker02.vm.provider "virtualbox" do |v|
            v.name = "docker02"
            v.memory = 2048
            v.cpus = 4
          end
          docker02.vm.network "public_network", bridge: "Killer E2200 Gigabit Ethernet Controller", ip: "192.168.1.237"
        # Initialization scripts
        docker02.vm.provision "shell", path: "./scripts/docker_init.sh"
        docker02.vm.provision "shell", path: "./scripts/worker_swarm_join.sh"
    end
    
    config.vm.define "docker03" do |docker03|
        docker03.vm.box = "generic/ubuntu2004"
        docker03.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        docker03.vm.hostname = "docker03.dob.lab"
        docker03.vm.provider "virtualbox" do |v|
            v.name = "docker03"
            v.memory = 2048
            v.cpus = 4
          end
          docker03.vm.network "public_network", bridge: "Killer E2200 Gigabit Ethernet Controller", ip: "192.168.1.238"
        # Initialization scripts
        docker03.vm.provision "shell", path: "./scripts/docker_init.sh"
        docker03.vm.provision "shell", path: "./scripts/worker_swarm_join.sh"
    end
end