Vagrant.configure("2") do |config|

    config.vm.define "vm" do |vm|
        vm.vm.box = "generic/ubuntu2004"
        vm.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        vm.vm.hostname = "vm"
        vm.vm.provider "virtualbox" do |v|
            v.name = "k8s01"
            v.memory = 2048
            v.cpus = 2
          end
          config.vm.network "private_network", ip: "192.168.99.101"
    end
end