Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    (1..3).each do |i|
        config.vm.define "k8s-#{i}" do |k8s|
            k8s.vm.box = "generic/ubuntu2004"
            k8s.vm.synced_folder ".", "/vagrant", type: "virtualbox"
            k8s.vm.hostname = "k8s-#{i}"
            k8s.vm.provider "virtualbox" do |v|
                v.name = "k8s#{i}"
                v.memory = 2048
                v.cpus = 2
            end
            k8s.vm.network "private_network", ip: "192.168.99.10#{i}"
            k8s.vm.network "forwarded_port", guest: 22, host: "1000#{i}"
            k8s.vm.provision "shell", inline: <<EOS
echo "* Updating mirrors urls"
sudo sed -i 's/us/bg/g' /etc/apt/sources.list
echo "* Updating mirrors"
sudo apt update

#echo "* Upgrading packages"
#sudo apt upgrade -y

echo "* Installing docker"
sudo apt install docker.io -y

echo "* Start and enable docker"
sudo systemctl start docker
sudo systemctl enable docker

echo "* Install apt-transport-https and curl"
sudo apt install apt-transport-https curl -y

echo "* Add Kubernetes signing key"
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add

echo "* Add Kubernetes repo"
sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"

echo "* Install Kubernetes"
sudo apt install kubeadm kubelet kubectl kubernetes-cni -y

echo "* Disable swap"
sudo swapoff -a
sudo sed -i '/ swap / s/^/#/' /etc/fstab

#
# Kubernetes Master Node Setup
#

echo "* Initialize Kubernetes"
# We need to specify the cidr network, otherwise coredns will be stuck on ContainerCreating
sudo kubeadm init --pod-network-cidr=10.244.0.0/16

echo "* Regular user command setup"
mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

echo "* Apply pod network"
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml

EOS
        end
    end
end